---
- hosts: ALL_SWITCHES
  gather_facts: no
  connection: local
 
  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: IOS | Is SNMP3 Enabled?
    ios_command:
      provider: "{{ provider }}"
      commands:
        - "sh run | i snmp-server group networkservices v3 auth"
    register: snmp

  - debug: msg="{{ snmp.stdout }}"
