---
- hosts: ALL_ROUTERS
  gather_facts: no
  connection: local
 
  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: IOS | enable SCP
    ios_config:
      provider: "{{ provider }}"
      lines: 
        - ip scp server enable
