---
- hosts: ALL_SWITCHES
  gather_facts: no
  connection: local
 
  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: IOS | Reload in 12 Hours
    ios_command:
      provider: "{{ provider }}"
      commands:
        - reload in 12:00
    register: memory

  - debug: msg="{{ memory.stdout }}"
